from __future__ import annotations


DEFAULT_WORDLIST = [

    #
    # Admin / auth panels
    #

    "admin",
    "administrator",
    "admins",
    "adminpanel",
    "admin_panel",
    "admin-panel",
    "administration",
    "manage",
    "management",
    "manager",
    "dashboard",
    "dashboards",
    "panel",
    "cpanel",
    "controlpanel",
    "control",
    "console",
    "login",
    "logout",
    "signin",
    "sign-in",
    "signup",
    "sign-up",
    "register",
    "auth",
    "authenticate",
    "authentication",
    "oauth",
    "sso",
    "session",
    "account",
    "accounts",
    "profile",
    "user",
    "users",
    "member",
    "members",
    "portal",
    "secure",
    "private",
    "internal",
    "backend",
    "back-end",
    "root",
    "superadmin",
    "moderator",
    "staff",

    #
    # API / docs
    #

    "api",
    "api/v1",
    "api/v2",
    "api/v3",
    "apidocs",
    "api-docs",
    "docs",
    "documentation",
    "doc",
    "swagger",
    "swagger-ui",
    "swagger.json",
    "swagger.yaml",
    "openapi",
    "openapi.json",
    "graphql",
    "graphiql",
    "playground",
    "rest",
    "restapi",
    "soap",
    "wsdl",
    "rpc",
    "grpc",
    "webhook",
    "webhooks",
    "callback",

    #
    # Config / env / secrets
    #

    "config",
    "configs",
    "configuration",
    ".env",
    ".env.local",
    ".env.production",
    ".env.dev",
    ".env.backup",
    "env",
    "environment",
    "settings",
    "settings.py",
    "settings.json",
    "web.config",
    "app.config",
    "appsettings.json",
    "config.php",
    "config.json",
    "config.yml",
    "config.yaml",
    "config.xml",
    "config.ini",
    "database.yml",
    "secrets",
    "secret",
    "secrets.json",
    "credentials",
    "credentials.json",
    ".htaccess",
    ".htpasswd",
    "wp-config.php",
    "wp-config.php.bak",
    "local.settings.json",

    #
    # Backup / archive files
    #

    "backup",
    "backups",
    "backup.zip",
    "backup.tar.gz",
    "backup.sql",
    "backup.tar",
    "backup.rar",
    "backup.7z",
    "backup.old",
    "backup_old",
    "old",
    "old.zip",
    "site.zip",
    "site.tar.gz",
    "www.zip",
    "database.sql",
    "db.sql",
    "dump.sql",
    "data.sql",
    "db_backup.sql",
    "backup.db",
    "backup.sqlite",
    ".bak",
    "index.php.bak",
    "index.html.bak",

    #
    # Version control / dev leftovers
    #

    ".git",
    ".git/config",
    ".git/HEAD",
    ".gitignore",
    ".gitlab-ci.yml",
    ".github",
    ".svn",
    ".svn/entries",
    ".hg",
    ".bzr",
    ".DS_Store",
    ".idea",
    ".vscode",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    ".dockerignore",
    "Makefile",
    "Vagrantfile",
    "composer.json",
    "composer.lock",
    "package.json",
    "package-lock.json",
    "yarn.lock",
    "requirements.txt",
    "Pipfile",
    "Pipfile.lock",
    "Gemfile",
    "Gemfile.lock",
    "pom.xml",
    "build.gradle",

    #
    # Uploads / static / media
    #

    "uploads",
    "upload",
    "files",
    "file",
    "media",
    "assets",
    "static",
    "public",
    "images",
    "img",
    "css",
    "js",
    "fonts",
    "downloads",
    "download",
    "documents",
    "storage",
    "tmp",
    "temp",
    "cache",
    "logs",
    "log",
    "log.txt",
    "error.log",
    "access.log",
    "debug.log",

    #
    # CMS-specific
    #

    "wp-admin",
    "wp-login.php",
    "wp-content",
    "wp-content/uploads",
    "wp-content/plugins",
    "wp-content/themes",
    "wp-includes",
    "wp-json",
    "wp-json/wp/v2/users",
    "xmlrpc.php",
    "administrator/index.php",
    "joomla",
    "drupal",
    "user/login",
    "sites/default/files",
    "typo3",
    "umbraco",
    "craft",
    "magento",
    "shopify",

    #
    # Info disclosure / debug endpoints
    #

    "phpinfo.php",
    "info.php",
    "test.php",
    "debug",
    "debug.php",
    "trace",
    "status",
    "health",
    "healthcheck",
    "health-check",
    "ping",
    "version",
    "version.json",
    "actuator",
    "actuator/health",
    "actuator/env",
    "metrics",
    "server-status",
    "server-info",
    "elmah.axd",
    "trace.axd",

    #
    # Cloud / infra / CI
    #

    ".aws",
    ".aws/credentials",
    "aws.yml",
    ".ssh",
    ".ssh/id_rsa",
    "id_rsa",
    "terraform.tfstate",
    "terraform.tfvars",
    "serverless.yml",
    "kubeconfig",
    "k8s",
    "jenkins",
    "Jenkinsfile",
    ".circleci",
    ".travis.yml",

    #
    # Misc common paths
    #

    "about",
    "contact",
    "help",
    "support",
    "faq",
    "search",
    "sitemap.xml",
    "robots.txt",
    "security.txt",
    ".well-known/security.txt",
    "humans.txt",
    "crossdomain.xml",
    "clientaccesspolicy.xml",
    "favicon.ico",
    "index",
    "index.html",
    "index.php",
    "home",
    "app",
    "app.js",
    "main.js",
    "bundle.js",
    "config.js",
    "settings.js",
]